# Generated by Django 5.1.5 on 2025-04-01 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='physician',
            name='specialization',
        ),
        migrations.AddField(
            model_name='physician',
            name='specialisation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
