# Generated by Django 5.1.5 on 2025-04-01 04:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0002_remove_physician_specialization_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientillness',
            name='patient',
        ),
        migrations.AddField(
            model_name='patientillness',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='illnesses', to=settings.AUTH_USER_MODEL),
        ),
    ]
