# Generated by Django 5.1.5 on 2025-04-01 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0003_remove_patientillness_patient_patientillness_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientillness',
            name='physician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='docs', to='userauth.physician'),
        ),
    ]
